const NAME_OR_PASSWORD_IS_REQUIRED = 'NAME_OR_PASSWORD_IS_REQUIRED';
const NAME_IS_EXISTS = 'NAME_IS_EXISTS';
const NAME_DOES_NOT_EXISTS = 'NAME_DOES_NOT_EXISTS';
const PASSWORD_IS_ERROR = 'PASSWORD_IS_ERROR';
const UNAUTHORIZAATION = 'UNAUTHORIZAATION';
const UNPERMISSION = 'UNPERMISSION';
const ERROR_REQUEST = 'ERROR_REQUEST';
const SQL_ERROR = 'SQL_ERROR';

module.exports = {
  NAME_OR_PASSWORD_IS_REQUIRED,
  NAME_IS_EXISTS,
  NAME_DOES_NOT_EXISTS,
  PASSWORD_IS_ERROR,
  UNAUTHORIZAATION,
  UNPERMISSION,
  ERROR_REQUEST,
  SQL_ERROR,
};
