const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const DELETE_SUCCESS = 'DELETE_SUCCESS';
const PATCH_SUCCESS = 'PATCH_SUCCESS';
const CREATE_SUCCESS = 'CREATE_SUCCESS';
const COMMENT_SUCCESS = 'COMMENT_SUCCESS';
const MOMENT_SUCCESS = 'MOMENT_SUCCESS';
const PUBLIC_SUCCESS = 'PUBLIC_SUCCESS';
module.exports = {
  LOGIN_SUCCESS,
  DELETE_SUCCESS,
  PATCH_SUCCESS,
  CREATE_SUCCESS,
  COMMENT_SUCCESS,
  MOMENT_SUCCESS,
  PUBLIC_SUCCESS,
};
